#!/usr/bin/env bash
# This script redirects Nginx server to another page
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
new='server_name  _;\n\trewrite ^\/redirect_me https:\/\/blog.techresolver.tech permanent;'
sudo sed -i "s/server_name _;/$new/" /etc/nginx/sites-enabled/default
sudo service nginx restart
