#!/usr/bin/env bash
# This bash script displays the content of file /etc/passwd
# Using the while loop + IFS

IFS=':'
while read -r user_name passwd uid gid uid_info home_directory command_shell
do
   echo "The user $user_name is part of the $gid gang, lives in $home_directory and rides $command_shell. $uid's place is protected by the passcode $passwd, more info about the user here: $uid_info"
done < /etc/passwd
