#!/usr/bin/env bash
# This script displays the time from 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ]
do
    echo "hour: $hour"
    for ((number=1; number <= 59; number++))
    do
        echo "$number"
    done
    ((hour++))
done
