#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

hosts="/etc/hosts"
new_host="$HOME/.hosts.new"

cp "$hosts" "$new_host"

sed -i "s/[^#].*\tlocalhost$//" "$new_host"
sed -i "s/[^#].*\tfacebook\.com$//" "$new_host"

echo "127.0.0.2		localhost" > "$new_host"
echo "8.8.8.8	facebook.com" > "$new_host"

cp -f "$new_host" "$hosts"
