#!/usr/bin/env bash
# This script changes the user of nginx to nginx and configures nginx to listen on port 8080
sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
# new_port='listen 8080 default_server;'
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apche2
sudo -u nginx service nginx restart
