#!/usr/bin/env bash
# This script changes the user of nginx to nginx and configures nginx to listen on port 8080
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
new_port='listen 8080 default_server;'
sudo sed -i "s/listen 80 default_server;/$new_port/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
