#!/usr/bin/env bash
# This script fixes the error with shotrter lines of code
sed -i "s/user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
